# Render Configuration for SBS Project
# This file should be placed in the root directory of your repository

services:
  - type: web
    name: sbs-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d28lj7ggjchc73bqgdj0-a.oregon-postgres.render.com:5432/securebanking
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres1
      - key: SPRING_DATASOURCE_PASSWORD
        value: Y0tzdcpJTzauyiwlCpNvEW0Z4mtth5vK
      - key: SPRING_REDIS_HOST
        value: red-d28lk8muk2gs73fg5t4g.redis.production.com
      - key: SPRING_REDIS_PORT
        value: "6379"
      - key: SPRING_REDIS_PASSWORD
        value: ""
      - key: REDIS_ENABLED
        value: "true"
      - key: JWT_SECRET
        value: lcft1vbW2P06txh4+AxBi80+czj6r5Nw8f+qayQZyZE=
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: konjetisaketh24@gmail.com
      - key: MAIL_PASSWORD
        value: zaok luhq duvx arlf
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app
    healthCheckPath: /actuator/health 